{var $robots = noindex}

{block #content}

<div class="container">

	<div class="navbar-form navbar-right">
		<form method="get" class="pull-left">
			<select id="languageChanger" name='language_id_change' class="form-control">
				{foreach $languages as $l}
					<option value="{$l->getId()}" {if $l->getId() == $language->getId()}selected{/if}>{$l->getName()}</option>
				{/foreach}
			</select>
			<input type="submit" value="{_'Change language'}" />
		</form>
	</div>

	{form signInForm class => 'form-signin'}
			<h2 class="form-signin-heading">{_'User login'}</h2>
			{input username class => 'form-control'}
			{input password class => 'form-control'}
			<label class="checkbox">
			  {input remember} {label remember /}
			</label>
			{input send class => "btn btn-lg btn-primary btn-block"}
	{/form}
</div> <!-- /container -->

{/block}
